name: traceit-backend
version: 0.1.0.0
license: BSD3
author: "FIT Group 28"
maintainer: "accounts@cedric.app"
copyright: "2022 FIT Group 28"

synopsis: INSERT HERE
category: INSERT HERE

description: Please see the README on GitHub.

dependencies:
  - base >= 4.7 && < 5
  - sqlite-simple
  - text
  - bytestring
  - mtl
  - containers
  - text-show
  - wai-extra
  - servant-server
  - warp
  - wai-cors
  - aeson
  - openapi3
  - servant-openapi3

library:
  source-dirs: src
  verbatim:
    default-language: GHC2021

executables:
  t-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - traceit-backend
    verbatim:
      default-language: GHC2021
