name: t
version: 0.1.0.0
license: BSD3
author: "Cedric Liang"
maintainer: "cedric@cedric.app"
copyright: "2022 Cedric Liang"

synopsis: INSERT HERE
category: INSERT HERE

description: Please see the README on GitHub.

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  verbatim:
    default-language: GHC2021

executables:
  t-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - t
    verbatim:
      default-language: GHC2021
