version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    restart: always
    env_file:
      - db.env # configure postgres
    ports:
        - '5432:5432'

    volumes:
      - ./sql/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh #init data
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      # presist data
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  database-data: # named volumes can be managed easier using docker-compose